# Generated by Django 3.1.2 on 2020-11-21 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_neg', models.CharField(max_length=100)),
                ('blogID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.blog')),
            ],
        ),
    ]
