# Generated by Django 3.1.2 on 2020-11-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
